"""empty message

Revision ID: f757913f4cd4
Revises: 
Create Date: 2024-11-18 14:31:43.897841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f757913f4cd4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('type_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('name_ru', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_en'),
    sa.UniqueConstraint('name_ru')
    )
    op.create_table('suspicious_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_event', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('was_notified', sa.Boolean(), nullable=False),
    sa.Column('description_event', sa.String(length=255), nullable=False),
    sa.Column('user_initiated_event', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['type_event'], ['type_event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suspicious_event')
    op.drop_table('type_event')
    # ### end Alembic commands ###
