services:
  backend:
    container_name: 'backend_sem'
    build:
      context: .
    ports:
      - "8011:8011"
    env_file:
      - ".env"
    networks:
      - sem

  nginx:
    image: nginx:latest
    container_name: 'nginx'
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - sem
    depends_on:
      - backend

networks:
    sem:
        external: true