services:
  backend:
    container_name: 'backend_sem'
    build:
      context: .
    ports:
      - "8011:8011"
    env_file:
      - ".env"
    networks:
      - asbp

networks:
    asbp:
        external: true